### ISSUE TITLE
Where is the ATT documentation to this and other useful endpoints like service availability? Any help would be appreciated

### ISSUE THREAD

**Issue by Bucanero06** [sithpow/att_availability_checker#2]

**Comment by s-mil** [comment]
@Bucanero06 I'm not sure of any documentation from ATT on this API,I mainly made this to help me find houses that have fiber that were potentials for me to move to.

So if you look at the unfiltered JSON there are multiple fields that can indicate various levels of service availability is there is there something in particular you are looking for. 
I am planning to add a --raw option to dump the JSON instead of the currently filtered boolean

**Comment by s-mil** [comment]
Raw feature added
